


print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")
print("CIAO SONO PARTITO!!!")