version: "3.3"


services:
  batch-spark:
    build: ./batch_preprocessing_analysis
    image: batch-spark:compose
    networks:
      - my-network
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./HomeC.csv:/input/HomeC.csv

  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra
  #   networks:
  #     - my-network
  #   ports:
  #     - 9042:9042
  #   volumes:
  #     - ./cassandra_db/script:/docker-entrypoint.sh
  #     - ./cassandra_db/data:/var/lib/cassandra
  #   command: >
  #     bash ./docker-entrypoint.sh/execute-cql.sh


  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra
  #   networks:
  #     - my-network
  #   ports:
  #     - "9042:9042"
  #   environment:
  #     - "MAX_HEAP_SIZE=256M"
  #     - "HEAP_NEWSIZE=128M"
  #   volumes:
  #     - ./cassandra_db/data:/var/lib/cassandra
      # - ./cassandra_db/script:/docker-entrypoint-initdb.d
    # command: bash -c 'sleep 10 && cqlsh -f /init-script.cql cassandra'


networks:
  my-network:
    driver: bridge